# endorsed-config.yaml
# VERSION 1.0.0

#------------------------
# Authentication Domains \
#------------------------------------------------------------------------------
# This section defines where user authentication will
# occur.
auth: 
  uri: "https://auth.openshift.io"

#-----------------------
# Github Authentication \
#------------------------------------------------------------------------------
# This section defines github authentication
github: 
    clientID: "a0e1ce33654a8446356b"
    clientSecret: "003e451564af39a5e29f768cbb9bcfd749577a31"

#-----------------------
# Sentry Authentication \
#------------------------------------------------------------------------------
# This section defines sebtry authentication
sentry:
    dsn: "https://b35571d43def4f169fd671d33560e0bf:126335bb736340f2850a293d77904400@errortracking.prod-preview.openshift.io/34"

#---------------------------
# Rest API Configuration    \
#------------------------------------------------------------------------------
# This section defines the url used by swagger to create the rest-api.
server:
  host: "localhost"
  port: 8099